version: '3'

networks:
  local_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.1.0/24

services:
  mysql:
    image: 'mysql:8.0.17'
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      local_net:
        ipv4_address: 172.12.1.2
  redis-mq:
    image: 'redis:5.0.5'
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - 6379:6379
    networks:
      local_net:
        ipv4_address: 172.12.1.3
  api-server:
    build:
      context: .
      dockerfile: apiserver/Dockerfile
      args:
        - WORKER_COUNT=1
    ports:
      - 80:8080
    environment:
      ENV: dev
      API_SERVER__MYSQL__HOST: 172.12.1.2
      API_SERVER__MYSQL__USER: root
      API_SERVER__MYSQL__PASSWORD: mysql_password
      API_SERVER__REDIS__HOST: 172.12.1.3
      API_SERVER__REDIS__PASSWORD: redis_password
    networks:
      local_net:
        ipv4_address: 172.12.1.4
    restart: unless-stopped
    depends_on:
      - mysql
      - redis-mq
  push-worker:
    build:
      context: .
      dockerfile: worker/push/fcm/Dockerfile
    environment:
      ENV: dev
      PUSH_WORKER__POOL_SIZE: 1
      PUSH_WORKER__REDIS__PASSWORD: redis_password
      PUSH_WORKER__REDIS__HOST: 172.12.1.3
      PUSH_WORKER__FIREBASE__SERVER_KEY: ${PUSH_WORKER__FIREBASE__SERVER_KEY}
    networks:
      local_net:
        ipv4_address: 172.12.1.5
    restart: unless-stopped
    depends_on:
      - mysql
      - redis-mq
  result-worker:
    build:
      context: .
      dockerfile: worker/result/Dockerfile
    environment:
      ENV: dev
      RESULT_WORKER__POOL_SIZE: 1
      RESULT_WORKER__MYSQL__HOST: 172.12.1.2
      RESULT_WORKER__MYSQL__USER: root
      RESULT_WORKER__MYSQL__PASSWORD: mysql_password
      RESULT_WORKER__REDIS__PASSWORD: redis_password
      RESULT_WORKER__REDIS__HOST: 172.12.1.3
    networks:
      local_net:
        ipv4_address: 172.12.1.6
    restart: unless-stopped
    depends_on:
      - mysql
      - redis-mq