version: '3'

networks:
  local_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.1.0/24

services:
  redis-mq:
    image: 'redis:5.0.5'
    command: redis-server --appendonly yes --requirepass password
    ports:
      - 6379:6379
    networks:
      local_net:
        ipv4_address: 172.12.1.3
  push-worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      ENV: dev
      PUSH_WORKER__REDIS__PASSWORD: password
      PUSH_WORKER__REDIS__HOST: 172.12.1.3
      PUSH_WORKER__FIREBASE__SERVER_KEY: ${PUSH_WORKER__FIREBASE__SERVER_KEY}
    networks:
      local_net:
        ipv4_address: 172.12.1.5
    restart: unless-stopped